IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
IF SCHEMA_ID(N'HOSPITAL_SYSTEM') IS NULL EXEC(N'CREATE SCHEMA [HOSPITAL_SYSTEM];');

CREATE TABLE [HOSPITAL_SYSTEM].[DEPARTMENTS] (
    [DEPT_ID] int NOT NULL IDENTITY,
    [DEPT_NAME] varchar(50) NOT NULL,
    CONSTRAINT [PK__DEPARTME__512A59AC4D33B8B5] PRIMARY KEY ([DEPT_ID])
);

CREATE TABLE [Users] (
    [Id] int NOT NULL IDENTITY,
    [TC] nvarchar(max) NOT NULL,
    [Password] nvarchar(max) NOT NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY ([Id])
);

CREATE TABLE [HOSPITAL_SYSTEM].[CLINICS] (
    [CLINIC_ID] int NOT NULL IDENTITY,
    [CLINIC_NUMBER] int NOT NULL,
    [DEPT_ID] int NULL,
    [DOCTOR_ID] int NULL,
    CONSTRAINT [PK__CLINICS__7A56A460F09ACA09] PRIMARY KEY ([CLINIC_ID]),
    CONSTRAINT [FK_CLINICS_DEPARTMENTS] FOREIGN KEY ([DEPT_ID]) REFERENCES [HOSPITAL_SYSTEM].[DEPARTMENTS] ([DEPT_ID])
);

CREATE TABLE [HOSPITAL_SYSTEM].[PATIENTS] (
    [PATIENT_ID] int NOT NULL IDENTITY,
    [PATIENT_NAME] varchar(50) NOT NULL,
    [DATE_OF_BIRTH] date NOT NULL,
    [GENDER] varchar(10) NOT NULL,
    [PHONE] varchar(15) NULL,
    [UserId] int NOT NULL,
    CONSTRAINT [PK__PATIENTS__AA0B6068ECFD06AA] PRIMARY KEY ([PATIENT_ID]),
    CONSTRAINT [FK_PATIENTS_Users_UserId] FOREIGN KEY ([UserId]) REFERENCES [Users] ([Id]) ON DELETE CASCADE
);

CREATE TABLE [HOSPITAL_SYSTEM].[DOCTORS] (
    [DOCTOR_ID] int NOT NULL IDENTITY,
    [DOCTOR_NAME] varchar(50) NOT NULL,
    [SPECIALIZATION] varchar(50) NOT NULL,
    [PHONE] varchar(15) NOT NULL,
    [EMAIL] varchar(100) NULL,
    [CLINIC_ID] int NULL,
    CONSTRAINT [PK__DOCTORS__596ABDB06355F749] PRIMARY KEY ([DOCTOR_ID]),
    CONSTRAINT [FK_DOCTORS_CLINICS] FOREIGN KEY ([CLINIC_ID]) REFERENCES [HOSPITAL_SYSTEM].[CLINICS] ([CLINIC_ID])
);

CREATE TABLE [HOSPITAL_SYSTEM].[APPOINTMENTS] (
    [APPOINTMENT_ID] int NOT NULL IDENTITY,
    [THE_DATE] date NOT NULL,
    [THE_TIME] time NOT NULL,
    [THE_STATUS] varchar(10) NOT NULL,
    [DOCTOR_ID] int NULL,
    [PATIENT_ID] int NULL,
    [CLINIC_ID] int NULL,
    CONSTRAINT [PK__APPOINTM__49B308C65E500E5D] PRIMARY KEY ([APPOINTMENT_ID]),
    CONSTRAINT [FK_APPOINTMENTS_CLINICS] FOREIGN KEY ([CLINIC_ID]) REFERENCES [HOSPITAL_SYSTEM].[CLINICS] ([CLINIC_ID]),
    CONSTRAINT [FK_APPOINTMENTS_DOCTORS] FOREIGN KEY ([DOCTOR_ID]) REFERENCES [HOSPITAL_SYSTEM].[DOCTORS] ([DOCTOR_ID]),
    CONSTRAINT [FK_APPOINTMENTS_PATIENTS] FOREIGN KEY ([PATIENT_ID]) REFERENCES [HOSPITAL_SYSTEM].[PATIENTS] ([PATIENT_ID])
);

CREATE INDEX [IX_APPOINTMENTS_CLINIC_ID] ON [HOSPITAL_SYSTEM].[APPOINTMENTS] ([CLINIC_ID]);

CREATE INDEX [IX_APPOINTMENTS_DOCTOR_ID] ON [HOSPITAL_SYSTEM].[APPOINTMENTS] ([DOCTOR_ID]);

CREATE INDEX [IX_APPOINTMENTS_PATIENT_ID] ON [HOSPITAL_SYSTEM].[APPOINTMENTS] ([PATIENT_ID]);

CREATE INDEX [IX_CLINICS_DEPT_ID] ON [HOSPITAL_SYSTEM].[CLINICS] ([DEPT_ID]);

CREATE INDEX [IX_DOCTORS_CLINIC_ID] ON [HOSPITAL_SYSTEM].[DOCTORS] ([CLINIC_ID]);

CREATE UNIQUE INDEX [IX_PATIENTS_UserId] ON [HOSPITAL_SYSTEM].[PATIENTS] ([UserId]);

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20260819112929_InitialCreate', N'10.0.7');

COMMIT;
GO

