// <auto-generated />
using System;
using Data_Accese_Layer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Accese_Layer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819112929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data_Accese_Layer.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("APPOINTMENT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int?>("ClinicId")
                        .HasColumnType("int")
                        .HasColumnName("CLINIC_ID");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DOCTOR_ID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PATIENT_ID");

                    b.Property<DateOnly>("TheDate")
                        .HasColumnType("date")
                        .HasColumnName("THE_DATE");

                    b.Property<string>("TheStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("THE_STATUS");

                    b.Property<TimeOnly>("TheTime")
                        .HasColumnType("time")
                        .HasColumnName("THE_TIME");

                    b.HasKey("AppointmentId")
                        .HasName("PK__APPOINTM__49B308C65E500E5D");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("APPOINTMENTS", "HOSPITAL_SYSTEM");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Clinic", b =>
                {
                    b.Property<int>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CLINIC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicId"));

                    b.Property<int>("ClinicNumber")
                        .HasColumnType("int")
                        .HasColumnName("CLINIC_NUMBER");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DEPT_ID");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DOCTOR_ID");

                    b.HasKey("ClinicId")
                        .HasName("PK__CLINICS__7A56A460F09ACA09");

                    b.HasIndex("DeptId");

                    b.ToTable("CLINICS", "HOSPITAL_SYSTEM");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DEPT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DEPT_NAME");

                    b.HasKey("DeptId")
                        .HasName("PK__DEPARTME__512A59AC4D33B8B5");

                    b.ToTable("DEPARTMENTS", "HOSPITAL_SYSTEM");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DOCTOR_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<int?>("ClinicId")
                        .HasColumnType("int")
                        .HasColumnName("CLINIC_ID");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DOCTOR_NAME");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SPECIALIZATION");

                    b.HasKey("DoctorId")
                        .HasName("PK__DOCTORS__596ABDB06355F749");

                    b.HasIndex("ClinicId");

                    b.ToTable("DOCTORS", "HOSPITAL_SYSTEM");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PATIENT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("GENDER");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PATIENT_NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PHONE");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId")
                        .HasName("PK__PATIENTS__AA0B6068ECFD06AA");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PATIENTS", "HOSPITAL_SYSTEM");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Appointment", b =>
                {
                    b.HasOne("Data_Accese_Layer.Entities.Clinic", "Clinic")
                        .WithMany("Appointments")
                        .HasForeignKey("ClinicId")
                        .HasConstraintName("FK_APPOINTMENTS_CLINICS");

                    b.HasOne("Data_Accese_Layer.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK_APPOINTMENTS_DOCTORS");

                    b.HasOne("Data_Accese_Layer.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_APPOINTMENTS_PATIENTS");

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Clinic", b =>
                {
                    b.HasOne("Data_Accese_Layer.Entities.Department", "Dept")
                        .WithMany("Clinics")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK_CLINICS_DEPARTMENTS");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Doctor", b =>
                {
                    b.HasOne("Data_Accese_Layer.Entities.Clinic", "Clinic")
                        .WithMany("Doctors")
                        .HasForeignKey("ClinicId")
                        .HasConstraintName("FK_DOCTORS_CLINICS");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Patient", b =>
                {
                    b.HasOne("Data_Accese_Layer.Entities.Users", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Data_Accese_Layer.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Clinic", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Department", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Data_Accese_Layer.Entities.Users", b =>
                {
                    b.Navigation("Patient")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
